apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: analytics-workspace-management
  namespace: ${analytics_workspace_management_namespace}
  annotations:
    xlscsde.nhs.uk/flux-branch: ${analytics_workspace_management_branch}
spec:
  targetNamespace: ${analytics_workspace_management_namespace}
  releaseName: analytics-workspace-management
  chart:
    spec:
      chart: analytics-workspace-management
      version: ${analytics_workspace_management_chart_version}
      sourceRef:
        kind: HelmRepository
        name: analytics-workspace-management
        namespace: ${analytics_workspace_management_namespace}
  interval: 5m0s
  install:
    remediation:
      retries: -1
    disableWait: true
    disableWaitForJobs: true
  upgrade:
    remediation:
      retries: -1
    disableWait: true
    disableWaitForJobs: true